export const SET_FILTER = "SET_FILTER";

export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";

export const ADD_PACKLIST = "ADD_PACKLIST"
export const DELETE_PACKLIST = "DELETE_PACKLIST"
export const EDIT_PACKLIST = "EDIT_PACKLIST"

/*
export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';

export const FETCH_PACKLISTS_PENDING = 'FETCH_PACKLISTS_PENDING';
export const FETCH_PACKLISTS_SUCCESS = 'FETCH_PACKLISTS_SUCCESS';
export const FETCH_PACKLISTS_ERROR = 'FETCH_PACKLISTS_ERROR'; */
